EWPP-1146: Update test coverage for template prefixes.
openeuropa/ecl-twig-loader pull request #28
Opened 2021-06-07 09:17 UTC by 22Alexandra

2021-06-15 13:25 UTC, ademarco requested changes
I'll leave inline comments.

2021-06-16 13:48 UTC, ademarco requested changes

2021-06-16 13:48 UTC, ademarco commented on src/Loader/EuropaComponentLibraryLoader.php
> +    public function __construct($namespaces, $paths = [], string $root = null, string $prefix = 'twig-component-', string $templatePrefix = '', string $extension = '.html.twig')
Let's not add `string ` typing here and below, as we didn't do it anywhere else in the class.

2021-06-16 13:48 UTC, ademarco commented on tests/EuropaComponentLibraryLoaderTest.php
> +    public function testLoader(string $name, string $expected, string $prefix, string $templatePrefix)
Same as above, let's not add typing.

2021-06-21 07:02 UTC, ademarco approved these changes

2021-06-21 07:06 UTC, imanoleguskiza approved these changes

2021-06-21 07:06 UTC, merged